services:
  grafana:

    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana

  
volumes:
  grafana-storage: